const cardData = [
  {
    id: 1,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/vkhcohhmqfczycw9vsar",
    name: "KFC",
    cuisines: "North Indian, Biryani, Tandoor",
    locality: "Sakchi, Jamshedpur",
    avgRating: 4.5,
    deliveryTime: 25,
  },
  {
    id: 2,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/dh0qsuqritnmbncwrni3",
    name: "Magic Momo",
    cuisines: "South Indian, Chinese",
    locality: "Bistupur, Jamshedpur",
    avgRating: 4.3,
    deliveryTime: 30,
  },
  {
    id: 3,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/hjao7sorzggaeqito6au",
    name: "Sai Resturant",
    cuisines: "South Indian, Chinese",
    locality: "Bistupur, Jamshedpur",
    avgRating: 4.5,
    deliveryTime: 30,
  },
  {
    id: 4,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/xph0vf5pvbxjf8xchwjk",
    name: "Champaran Handi",
    cuisines: "South Indian, Chinese",
    locality: "Bistupur, Jamshedpur",
    avgRating: 3.7,
    deliveryTime: 30,
  },
  {
    id: 5,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/ntcsuou2650qimnkrc3m",
    name: "Sai Resturant",
    cuisines: "South Indian, Chinese",
    locality: "Bistupur, Jamshedpur",
    avgRating: 3.8,
    deliveryTime: 30,
  },
  {
    id: 6,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/sidigb8zqjfrfpkrtqgl",
    name: "Family Dhaba",
    cuisines: "South Indian, Chinese",
    locality: "Bistupur, Jamshedpur",
    avgRating: 2.9,
    deliveryTime: 30,
  },
  {
    id: 7,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/uxgpy3bwmc5rsojmtw43",
    name: "Chaska Coffee",
    cuisines: "South Indian, Chinese",
    locality: "Bistupur, Jamshedpur",
    avgRating: 4.3,
    deliveryTime: 30,
  },
  {
    id: 8,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/nigqvxgzvyxtfjuqasgg",
    name: "Junction",
    cuisines: "South Indian, Chinese",
    locality: "Bistupur, Jamshedpur",
    avgRating: 4.1,
    deliveryTime: 30,
  },
  {
    id: 9,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/2274f59cb8efcfab1f446b195bcbda3b",
    name: "Shree Naivedyam",
    cuisines: "South Indian, Chinese",
    locality: "Bistupur, Jamshedpur",
    avgRating: 4.7,
    deliveryTime: 30,
  },
  {
    id: 10,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/mt2aggiscfl3yviatwng",
    name: "Bakery World",
    cuisines: "South Indian, Chinese",
    locality: "Bistupur, Jamshedpur",
    avgRating: 3.2,
    deliveryTime: 30,
  },
  {
    id: 11,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2024/4/15/9de3a721-5e96-41d2-bb3e-3cbeff47fbd3_870899.jpg",
    name: "Hira Sweets",
    cuisines: "South Indian, Chinese",
    locality: "Bistupur, Jamshedpur",
    avgRating: 4.8,
    deliveryTime: 30,
  },
  {
    id: 12,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/510fc7e0a265c4c71ef10f0406583373",
    name: "Spice Club",
    cuisines: "South Indian, Chinese",
    locality: "Bistupur, Jamshedpur",
    avgRating: 4.3,
    deliveryTime: 30,
  },
  {
    id: 13,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/ofjn39gnpkzhkllfishc",
    name: "Chinese Resturant",
    cuisines: "South Indian, Chinese",
    locality: "Bistupur, Jamshedpur",
    avgRating: 3.6,
    deliveryTime: 30,
  },
  {
    id: 14,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/b14cd9fc40129fcfb97aa7e621719d07",
    name: "The Veg Legacy",
    cuisines: "South Indian, Chinese",
    locality: "Bistupur, Jamshedpur",
    avgRating: 3.3,
    deliveryTime: 30,
  },
  {
    id: 15,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/xvyrclhxftulsglktaek",
    name: "Sai Resturant",
    cuisines: "South Indian, Chinese",
    locality: "Bistupur, Jamshedpur",
    avgRating: 4.2,
    deliveryTime: 30,
  },
];

// const cardData = [
//   {
//     id: 1,
//     img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/vkhcohhmqfczycw9vsar",
//     resName: "KFC",
//     cuisines: "North Indian, Biryani, Tandoor",
//     locality: "Sakchi, Jamshedpur",
//     ratings: "4.5",
//     time: 25,
//   },
//   {
//     id: 2,
//     img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/dh0qsuqritnmbncwrni3",
//     resName: "Magic Momo",
//     cuisines: "South Indian, Chinese",
//     locality: "Bistupur, Jamshedpur",
//     ratings: "3.2",
//     time: 30,
//   },
//   {
//     id: 3,
//     img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/hjao7sorzggaeqito6au",
//     resName: "Sai Resturant",
//     cuisines: "South Indian, Chinese",
//     locality: "Bistupur, Jamshedpur",
//     ratings: "4.7",
//     time: 30,
//   },
// ];

export default cardData;
